/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hasbullateam.escape_room;

/**
 *
 * @author giuse
 */
public class Menu extends javax.swing.JPanel {

    Runnable gotoEscapeRoom;
    Runnable gotoBattleShip;
    Runnable gotoPingPong;
    Runnable gotoTris;
    
    private boolean isShowedMinigameButton = false;
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setVisibileMinigameButton(false);
        
    }
    
    void setVisibileMinigameButton(boolean visible){
        this.isShowedMinigameButton = visible;
        buttonBattleShip.setVisible(visible);
        buttonTris.setVisible(visible);
        buttonPingPong.setVisible(visible);
    }
    
    
    public void setGotoEscapeRoom(Runnable gotoEscapeRoom){
        this.gotoEscapeRoom = gotoEscapeRoom;
    }
    
    public void setGotoBattleShip(Runnable gotoBattleShip){
        this.gotoBattleShip = gotoBattleShip;
    }
    
    public void setGotoTris(Runnable gotoTris){
        this.gotoTris = gotoTris;
    }
    
    public void setGotoPingPong(Runnable gotoPingPong){
        this.gotoPingPong = gotoPingPong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEscapeRoom = new javax.swing.JButton();
        buttonMiniGame = new javax.swing.JButton();
        buttonTris = new javax.swing.JButton();
        buttonBattleShip = new javax.swing.JButton();
        buttonPingPong = new javax.swing.JButton();

        buttonEscapeRoom.setText("Escape Room");
        buttonEscapeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEscapeRoomActionPerformed(evt);
            }
        });

        buttonMiniGame.setText("Mini Game");
        buttonMiniGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMiniGameActionPerformed(evt);
            }
        });

        buttonTris.setText("Tris");
        buttonTris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrisActionPerformed(evt);
            }
        });

        buttonBattleShip.setText("Battle Ship");
        buttonBattleShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBattleShipActionPerformed(evt);
            }
        });

        buttonPingPong.setText("Ping Pong");
        buttonPingPong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPingPongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPingPong)
                    .addComponent(buttonMiniGame)
                    .addComponent(buttonEscapeRoom)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonTris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBattleShip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonEscapeRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMiniGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBattleShip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPingPong)
                .addGap(0, 161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPingPongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPingPongActionPerformed
        this.gotoPingPong.run();
    }//GEN-LAST:event_buttonPingPongActionPerformed

    private void buttonBattleShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBattleShipActionPerformed
        this.gotoBattleShip.run();
    }//GEN-LAST:event_buttonBattleShipActionPerformed

    private void buttonTrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrisActionPerformed
        this.gotoTris.run();
    }//GEN-LAST:event_buttonTrisActionPerformed

    private void buttonMiniGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMiniGameActionPerformed
        setVisibileMinigameButton(!isShowedMinigameButton);
    }//GEN-LAST:event_buttonMiniGameActionPerformed

    private void buttonEscapeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEscapeRoomActionPerformed
        this.gotoEscapeRoom.run();
    }//GEN-LAST:event_buttonEscapeRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBattleShip;
    private javax.swing.JButton buttonEscapeRoom;
    private javax.swing.JButton buttonMiniGame;
    private javax.swing.JButton buttonPingPong;
    private javax.swing.JButton buttonTris;
    // End of variables declaration//GEN-END:variables
}
